Repository GSG-G8/book-website, pull requests merged in 2020-02, with the labels that each got.

#8 add file strucutre
  .gitignore
  public/404.html
  public/favicon.ico
  public/index.html
  public/js/dom.js
  public/style.css
  src/app.js
  src/controllers/bookfunction.js
  src/database/db_build.js
  src/database/db_build.sql
  src/database/db_connection.js
  src/index.js
  src/routes/book.js
  src/routes/index.js
Labels: Done, awaiting review

#10 setup project, initalize npm and required packages
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
Labels: awaiting review

#11 add the basic layout of main html page
  public/index.html
  public/style.css
Labels: awaiting review

#12 add page 404error and it's style
  public/404.html
  public/style.css
Labels: awaiting review

#13 create database
  src/database/db_build.sql
Labels: database

#15 create express server and add new input in html page
  public/index.html
  src/app.js
  src/index.js
Labels: awaiting review

#21 Db connection
  src/controllers/getBook.js
  src/database/db_build.js
  src/database/db_build.sql
  src/database/db_connection.js
Labels: awaiting review

#30 make getData function, rearrange database folder, make folder for test
  src/database/__test__/db.test.js
  src/database/config/db_build.js
  src/database/config/db_build.sql
  src/database/config/db_connection.js
  src/database/queries/getData.js
Labels: awaiting review

#33 dom manipulation
  public/index.html
  public/js/dom.js
Labels: javascript

#45 Display new book
  public/index.html
  public/js/dom.js
  src/database/config/db_connection.js
Labels: awaiting review
